# Generated by Django 4.2.7 on 2023-12-08 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_user_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(default='/blog/static/blog/images/blank-picture.png', upload_to='images'),
        ),
    ]
