# Generated by Django 4.2.7 on 2023-12-09 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_user_followers_user_following'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='followers',
            new_name='follower_count',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='following',
            new_name='following_count',
        ),
    ]
