# Generated by Django 4.2.7 on 2023-12-09 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_rename_followers_user_follower_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, default='A seasoned author', max_length=200, null=True),
        ),
    ]
