# Generated by Django 4.2.7 on 2023-12-21 12:28

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_alter_user_bio'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='user',
            name='follower_count',
        ),
        migrations.RemoveField(
            model_name='user',
            name='following_count',
        ),
        migrations.RemoveField(
            model_name='user',
            name='profile_picture',
        ),
    ]
