# Generated by Django 4.2.7 on 2023-12-05 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_category_options_category_category_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['-date']},
        ),
        migrations.AddField(
            model_name='tag',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='tag',
            name='tag_name',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
