# Generated by Django 4.2.7 on 2023-12-05 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_profile_collection'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['-date'], 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='story',
            options={'ordering': ['-date'], 'verbose_name_plural': 'Stories'},
        ),
        migrations.AddField(
            model_name='category',
            name='story_image',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
