# Generated by Django 4.2.7 on 2023-12-05 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_category_options_alter_story_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='collection_name',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='story',
            name='slug',
            field=models.SlugField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='story',
            name='story_heading',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='story',
            name='story_subtitle',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='story',
            name='text_contents',
            field=models.TextField(max_length=20000),
        ),
    ]
