# Generated by Django 4.2.7 on 2023-12-06 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_collection_collection_name_alter_story_slug_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='story_image',
            new_name='category_image',
        ),
        migrations.AddField(
            model_name='category',
            name='short_description',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
