# Generated by Django 4.2.7 on 2023-12-06 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_rename_story_image_category_category_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='short_description',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
