# Generated by Django 4.2.7 on 2023-12-07 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_story_recommemended'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='show_on_navigation_bar',
            field=models.BooleanField(default=False, help_text="No=Don't show, Yes=Show", null=True),
        ),
    ]
