# Generated by Django 4.2.7 on 2023-12-09 16:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0014_user_following_user_follower'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_following',
            name='user',
        ),
        migrations.AddField(
            model_name='user_following',
            name='users_to_follow',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='user_follower',
            name='user',
        ),
        migrations.AddField(
            model_name='user_follower',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
