# Generated by Django 4.2.7 on 2023-12-09 17:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0016_remove_user_following_users_to_follow_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_follower',
            name='new_follower',
        ),
        migrations.RemoveField(
            model_name='user_following',
            name='new_following',
        ),
        migrations.AddField(
            model_name='user_follower',
            name='new_follower',
            field=models.ManyToManyField(related_name='new_follower', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user_following',
            name='new_following',
            field=models.ManyToManyField(related_name='new_following', to=settings.AUTH_USER_MODEL),
        ),
    ]
