# Generated by Django 4.2.7 on 2023-12-10 13:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0018_remove_user_follower_new_follower_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='author_followers',
            field=models.ManyToManyField(related_name='author_followers', to=settings.AUTH_USER_MODEL),
        ),
    ]
