# Generated by Django 4.2.7 on 2023-12-11 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_remove_collection_collection_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='story',
        ),
        migrations.AddField(
            model_name='collection',
            name='story',
            field=models.ManyToManyField(to='blog.story'),
        ),
    ]
