# Generated by Django 4.2.7 on 2023-12-11 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_remove_collection_story_collection_story'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='collection_name',
            field=models.CharField(max_length=80, null=True),
        ),
    ]
