# Generated by Django 4.2.7 on 2023-12-14 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0026_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='comment',
            field=models.TextField(max_length=500, null=True),
        ),
    ]
