# Generated by Django 4.2.7 on 2023-12-14 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0028_profile_display_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='display_name',
            field=models.CharField(default='<django.db.models.query_utils.DeferredAttribute object at 0x00000209CDDD1F70> <django.db.models.query_utils.DeferredAttribute object at 0x00000209CEDA3980>', max_length=100, null=True),
        ),
    ]
