# Generated by Django 4.2.7 on 2023-12-15 06:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0030_alter_profile_display_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='author_following',
            field=models.ManyToManyField(related_name='author_following', to=settings.AUTH_USER_MODEL),
        ),
    ]
