# Generated by Django 4.2.7 on 2023-12-18 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0034_remove_user_following_new_following_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='follower_count',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
