# Generated by Django 4.2.7 on 2023-12-20 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0038_search'),
    ]

    operations = [
        migrations.AlterField(
            model_name='search',
            name='search_query',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
