# Generated by Django 4.2.7 on 2023-12-22 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0040_alter_category_category_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='story_image',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
    ]
