# Generated by Django 4.2.7 on 2023-12-22 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0041_alter_story_story_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_image',
            field=models.ImageField(null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='story',
            name='story_image',
            field=models.ImageField(upload_to='images'),
        ),
    ]
