from django.urls import path
from . import views

urlpatterns = [
    path("", views.home_page_view, name="home_page"),
    path("myblog", views.user_home_view, name="user_home"),
    path("onboarding", views.onboarding_view, name="onboarding"),
    path("categories", views.all_categories_view, name="all-categories"),
    path("signin", views.login_view, name="signin"),
    path("signup", views.signup_view, name="signup"),
    path("logout", views.logout_view, name="logout"),
    path("deactivate_account", views.deactivate_account, name="deactivate-account"),
    path("delete_account", views.delete_account, name="delete-account"),
    path("myblog/search", views.search_view, name="search"),
    path("myblog/search/author", views.author_search_view, name="author-search"),
    path("myblog/search/category", views.category_search_view, name="category-search"),
    path("myblog/share-your-story", views.write_story_view, name="write-story"),
    path("myblog/notifications", views.notifications_view, name="notifications"),
    path("myblog/notifications/story-reviews", views.story_reviews_view, name="story-reviews"),
    path("myblog/who-to-follow", views.who_to_follow_view, name="who-to-follow"),
    #path("myblog/author-profile", views.author_profile, name="author-profile"),
    #path("myblog/profile/copy-profile-link",views.copy_link, name="copy-profile-link"),
    path("myblog/profile", views.user_profile, name="user-profile"),
    path("myblog/profile/my-collections", views.my_collections_view, name="my-collections"),
    path("myblog/profile/following", views.following_view, name="following"),
    path("myblog/profile/follower", views.follower_view, name="follower"),
    path("myblog/profile/edit-profile", views.edit_profile_view, name="edit-profile"),
    path("myblog/profile/settings", views.settings_view, name="settings"),
    path("myblog/@<str:user_name>", views.author_profile, name="author-profile"),
    path("myblog/profile/@<str:user_name>", views.user_profile, name="user-profile"),
    path("home/from-the-community/<slug:home_cate_slug>", views.home_category_view, name="home_category"),
    path("myblog/<slug:chosen_cate_slug>",views.chosen_category_view, name="chosen_category"),
    path("categories/<slug:slug>", views.single_category_view, name="single-category"),
    path("categories/<slug:cate_slug>/<slug:post_slug>", views.post_details_view, name="post-details"),
]
